export enum StewardsMonth {
    YESTARE = "YESTARE",
    NARVINYE = "NARVINYE", NENIME = "NENIME", SULIME = "SULIME",
    TUILERE = "TUILERE",
    VIRESSE = "VIRESSE", LOTESSE = "LOTESSE", NARIE = "NARIE",
    LOENDE = "LOENDE",
    ENDERE = "ENDERE",
    CERMIE = "CERMIE", URIME = "URIME", YAVANNIE = "YAVANNIE",
    YAVIERE = "YAVIERE",
    NARQUELIE = "NARQUELIE", HISIME = "HISIME", RINGARE = "RINGARE",
    METTARE = "METTARE"
}
